### PR TITLE
Dashboard done

### PR DESCRIPTION
**Pull request by nouradeen**
- Dashboard Done, just need to fick the meal_question widget class to work on all screens
- Old files from the previous design now have the postfix <NAME>_OLD.dart
- Added a custom widget class (CustomDialogWidget)
- Added the comment `//TODO: DATABASE` in everyplace where we need to use the database to grab the data

### CODE REVIEW

**Review by Mnpn — CHANGES_REQUESTED** [review]
This looks pretty nice! I have a few questions/ideas though:
- :x: Do we need to keep the old files from the old design around? Unless we're for some reason relying on/using them (in which case they should not be "old"), there's no need to keep them in. Remember, we use Git and can access removed content by just browsing an older commit, so I don't think we should keep outdated files scattered about - it's better to delete them. (edit: haven't looked into it too much - are other parts of the app using them?)

- 💭  What do you think about making the button icons a bit smaller, and making the text larger and bold? (See Figma's "Dashboard 2")

- 💡 Should the "Next meal in blabla" text be bold? It might make it easier to read. ("Dashboard 2")

- 💭  I think either way is fine, but if you want to replace the button drop shadows with something more similar to the Figma "Dashboard 2" design, it appears you can use a box shadow from a BoxDecoration if you wrap the TextButton in a Container (I can't figure out how to apply a border to only some sides of a TextButton, appears impossible):
```dart
Container(
  decoration: BoxDecoration(
    borderRadius: BorderRadius.circular(7),
    boxShadow: [
      BoxShadow(
        color: widget.isNotYetButtonClicked ? Color.fromARGB(255, 161, 161, 161) : Color.fromARGB(255, 179, 123, 40), // e.g. Color.fromARGB(255, 0, 109, 56) for the other button
        blurRadius: 0,
        offset: Offset(0.0, 3)
       )],
    ),
    child: TextButton(
      onPressed: () {......
```
and removing `elevation: 3`, which ends up looking like this:

image

The current button style works too though, so maybe we should just stick with what's easiest - your call.

**Comment by nouradeen** [comment]
- We are using parts of the old design (check the login/signup in Figma), so I thought that we could keep them until the design is finished, then we don't need to write everything again. But if they are being saved in Github, we can delete them.
- I can run the command `dart fix --apply` and see what changes, should not affect the code itself
- The buttons are smaller, the text is bolder, etc... those things can be changed in seconds, so maybe focus on creating the screens, and edit the necessary when we have some kind of meeting?
- I can check out the code you provided for the shadows. I used `elevation: 3` because it saved me a lot of time :)

**Comment by Mnpn** [comment]
- Yep, you'll always be able to browse what was here in https://github.com/M-AboWarda/Elder-Care-app/tree/36e5380a88b925eb87590c1a4144befc532997f3
- Sounds good, I think it'll just auto-add consts and such and not change any functionality.
- Sure thing! We can do touch-ups and improvements as we go. Let's get UI implemented before we do any small-scale changes 👍 
- Makes sense! I don't mind it if we stick with the shadow if that's an easier/faster/less complicated solution.

**Review by Mnpn — APPROVED** [review]
This looks good to me!

**Pull request merged**
